# Use Maven to build the app
FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Use OpenJDK to run the app
FROM openjdk:17.0.1-jdk-slim
WORKDIR /app
COPY --from=build /app/target/catsforcuteness-0.0.1-SNAPSHOT.jar cats.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "cats.jar"]
